ALTER TABLE Item ADD
    CONSTRAINT Item_Cadastro
    FOREIGN KEY (id_cadastro)
    REFERENCES Cadastro (id)
    ON DELETE CASCADE
    NOT DEFERRABLE
    INITIALLY IMMEDIATE;

ALTER TABLE Item ADD
    CONSTRAINT Item_Produto
    FOREIGN KEY (id_produto)
    REFERENCES Produto (id)
    ON DELETE CASCADE
    NOT DEFERRABLE
    INITIALLY IMMEDIATE;

ALTER TABLE Item ADD
    CONSTRAINT Item_Venda
    FOREIGN KEY (id_venda)
    REFERENCES Venda (id)
    ON DELETE SET NULL
    NOT DEFERRABLE
    INITIALLY IMMEDIATE;

ALTER TABLE Nome ADD
    CONSTRAINT Nome_Produto
    FOREIGN KEY (id_produto)
    REFERENCES Produto (id)
    ON DELETE CASCADE
    NOT DEFERRABLE
    INITIALLY IMMEDIATE;

ALTER TABLE Produto ADD
    CONSTRAINT Produto_Marca
    FOREIGN KEY (id_marca)
    REFERENCES Marca (id)
    ON DELETE SET NULL
    NOT DEFERRABLE
    INITIALLY IMMEDIATE;